version: '2.25.0'
name: jobboard-stack

services:
  api:
    image: kapiaszczyk/job-board:example-cors
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-network
    environment:
      JDBC_DATABASE_USERNAME: api
      JDBC_DATABASE_PASSWORD: apipassword
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432
      JDBC_DATABASE_NAME: jobboard
      RATE_LIMIT_BUCKET_CAPACITY: 10
      RATE_LIMIT_REFILL_PERIOD_SECONDS: 1
      RATE_LIMIT_REFILL_TOKENS: 1
      CACHE_INITIAL_CAPACITY: 100
      CACHE_MAXIMUM_SIZE: 1000
      CACHE_EXPIRE_AFTER_WRITE_MINUTES: 1
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: apipassword
      POSTGRES_DB: jobboard
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    command: postgres -c log_statement=all
  ngnix:
    image: nginx:latest
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./docs:/usr/share/nginx/html/docs:ro
      - ./example:/usr/share/nginx/html/example:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mime.types:/etc/nginx/mime.types:ro

networks:
  postgres-network:
    driver: bridge