version: '2.25.0'
name: jobboard

services:
  api:
    image: kapiaszczyk/jobboard-api:0.0.2
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres-network
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: apipassword
      POSTGRES_DB: jobboard
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge