INSERT INTO technology (name, description) VALUES ('PortablE', 'Wall data two option rise author seek.');
INSERT INTO technology (name, description) VALUES ('CLIST', 'Choice institution marriage information tree road.');
INSERT INTO technology (name, description) VALUES ('Lite-C', 'Civil space ask night television.');
INSERT INTO technology (name, description) VALUES ('Hy', 'Leader interesting step civil ever high begin.');
INSERT INTO technology (name, description) VALUES ('Nemerle', 'Produce expert much bit middle.');
INSERT INTO technology (name, description) VALUES ('Max', 'Build student commercial enter.');
INSERT INTO technology (name, description) VALUES ('SML', 'Fast build my six describe prevent news.');
INSERT INTO technology (name, description) VALUES ('ECMAScript', 'Collection sea everyone threat break.');
INSERT INTO technology (name, description) VALUES ('G-code', 'Test player computer rule sort.');
INSERT INTO technology (name, description) VALUES ('DataFlex', 'Similar tonight window claim there.');
INSERT INTO technology (name, description) VALUES ('Jython', 'Mr light fly.');
INSERT INTO technology (name, description) VALUES ('SPIN', 'Serious vote all peace collection travel lay.');
INSERT INTO technology (name, description) VALUES ('FOIL', 'Wish sometimes whole natural pattern hear.');
INSERT INTO technology (name, description) VALUES ('Boo', 'Like whether whom production almost character.');
INSERT INTO technology (name, description) VALUES ('DYNAMO', 'Show return bill better point.');
INSERT INTO technology (name, description) VALUES ('Blockly', 'Reflect free final consumer new.');
INSERT INTO technology (name, description) VALUES ('Janus', 'Guy develop TV end.');
INSERT INTO technology (name, description) VALUES ('SuperCollider', 'Bad event most career notice.');
INSERT INTO technology (name, description) VALUES ('ML', 'Worker just worker operation.');
INSERT INTO technology (name, description) VALUES ('SR', 'Environment meet plan look space project relationship.');
INSERT INTO technology (name, description) VALUES ('SKILL', 'Soldier leave speak population effect maintain general surface.');
INSERT INTO technology (name, description) VALUES ('Hopscotch', 'Final five professional well state.');
INSERT INTO technology (name, description) VALUES ('AutoLISP', 'Especially player garden.');
INSERT INTO technology (name, description) VALUES ('Verse', 'Network moment find myself direction the month.');
INSERT INTO technology (name, description) VALUES ('ACC', 'Health training food reflect energy modern.');
INSERT INTO technology (name, description) VALUES ('Edinburgh IMP', 'And as trial situation happy.');
INSERT INTO technology (name, description) VALUES ('ColdFusion', 'Table student himself travel.');
INSERT INTO technology (name, description) VALUES ('BASIC', 'Contain relate vote body forward court.');
INSERT INTO technology (name, description) VALUES ('Powerhouse', 'President adult right by hope.');
INSERT INTO technology (name, description) VALUES ('GNU Ubiquitous Intelligent Language for Extensions', 'Since Mr human TV by research manage.');
INSERT INTO technology (name, description) VALUES ('Mortran', 'Out about perhaps never early.');
INSERT INTO technology (name, description) VALUES ('LLL', 'Difficult past possible customer.');
INSERT INTO technology (name, description) VALUES ('CFEngine', 'Benefit area western.');
INSERT INTO technology (name, description) VALUES ('Game Oriented Assembly Lisp', 'International quite spring if.');
INSERT INTO technology (name, description) VALUES ('IDL', 'Concern deal service record you writer.');
INSERT INTO technology (name, description) VALUES ('Ratfiv', 'Decade huge minute list soldier current.');
INSERT INTO technology (name, description) VALUES ('Swift', 'Charge memory price interest on ask look.');
INSERT INTO technology (name, description) VALUES ('Whiley', 'Writer serious mention whether yes.');
INSERT INTO technology (name, description) VALUES ('Visual FoxPro', 'Scientist really design less.');
INSERT INTO technology (name, description) VALUES ('LLL', 'Assume nation house me.');
INSERT INTO technology (name, description) VALUES ('WebAssembly', 'Turn employee buy still just.');
INSERT INTO technology (name, description) VALUES ('PROMAL', 'Before response similar.');
INSERT INTO technology (name, description) VALUES ('UNITY', 'Story article wrong.');
INSERT INTO technology (name, description) VALUES ('C', 'Performance bad six.');
INSERT INTO technology (name, description) VALUES ('Arc', 'Night let challenge woman.');
INSERT INTO technology (name, description) VALUES ('Squeak', 'School world including next whatever.');
INSERT INTO technology (name, description) VALUES ('OpenCL', 'Per image mind.');
INSERT INTO technology (name, description) VALUES ('Clean', 'Agree option participant ask scene half fly.');
INSERT INTO technology (name, description) VALUES ('CLIST', 'Sign design executive attack her not speak sense.');
INSERT INTO technology (name, description) VALUES ('Y', 'Leg week by listen behind conference.');
INSERT INTO technology (name, description) VALUES ('Hy', 'Also find fill already reduce they western.');
INSERT INTO technology (name, description) VALUES ('Elm', 'Too family necessary ability safe blood bad.');
INSERT INTO technology (name, description) VALUES ('P', 'Road former radio cell project require.');
INSERT INTO technology (name, description) VALUES ('.QL', 'Toward ball race itself though.');
INSERT INTO technology (name, description) VALUES ('E', 'Service trouble training amount test.');
INSERT INTO technology (name, description) VALUES ('Q#', 'Half bank whom history lawyer around side.');
INSERT INTO technology (name, description) VALUES ('Hume', 'At eight production.');
INSERT INTO technology (name, description) VALUES ('AmbientTalk', 'Find peace find let ten offer.');
INSERT INTO technology (name, description) VALUES ('Factor', 'Energy image firm.');
INSERT INTO technology (name, description) VALUES ('Flex', 'Especially well front.');
INSERT INTO technology (name, description) VALUES ('SKILL', 'After idea there science natural senior.');
INSERT INTO technology (name, description) VALUES ('Common Intermediate Language', 'School rather century quite suddenly style.');
INSERT INTO technology (name, description) VALUES ('MAD/I', 'Admit pick now forget.');
INSERT INTO technology (name, description) VALUES ('Nemerle', 'Crime Mr power produce strategy.');
INSERT INTO technology (name, description) VALUES ('PCASTL', 'Behavior plan between name course.');
INSERT INTO technology (name, description) VALUES ('Z++', 'Fall stay or mean represent.');
INSERT INTO technology (name, description) VALUES ('Scilab', 'Big tend as follow what way approach.');
INSERT INTO technology (name, description) VALUES ('S2', 'Entire degree alone article feel determine little program.');
INSERT INTO technology (name, description) VALUES ('Claire', 'Purpose community discussion front respond.');
INSERT INTO technology (name, description) VALUES ('Fjolnir', 'Rule hold home response actually economic various especially.');
INSERT INTO technology (name, description) VALUES ('Legoscript', 'Far woman true central live single.');
INSERT INTO technology (name, description) VALUES ('NESL', 'Character series serious I speech.');
INSERT INTO technology (name, description) VALUES ('Legoscript', 'Thing above home star soon.');
INSERT INTO technology (name, description) VALUES ('Picolisp', 'Law strategy computer.');
INSERT INTO technology (name, description) VALUES ('Squirrel', 'Still event travel respond beautiful but among.');
INSERT INTO technology (name, description) VALUES ('RPG', 'Minute activity vote piece.');
INSERT INTO technology (name, description) VALUES ('NetLogo', 'Same clearly within reality relate happen.');
INSERT INTO technology (name, description) VALUES ('Cayenne', 'Home fact as win public letter same.');
INSERT INTO technology (name, description) VALUES ('C#', 'Fine skin discuss gas rule.');
INSERT INTO technology (name, description) VALUES ('Join Java', 'Wait executive establish everybody economic hotel tend.');
INSERT INTO technology (name, description) VALUES ('XC', 'Ever key exist call.');
INSERT INTO technology (name, description) VALUES ('TELCOMP', 'Newspaper message move goal.');
INSERT INTO technology (name, description) VALUES ('Octave', 'Half seat listen us.');
INSERT INTO technology (name, description) VALUES ('Catrobat', 'Standard business really maybe hour.');
INSERT INTO technology (name, description) VALUES ('PHP', 'Professor amount matter style guy decision president cultural.');
INSERT INTO technology (name, description) VALUES ('Q', 'Body difference sure imagine central specific.');
INSERT INTO technology (name, description) VALUES ('Pascal Script', 'Voice its policy bill method.');
INSERT INTO technology (name, description) VALUES ('PeopleCode', 'Nice sure argue difference pick soon leg.');
INSERT INTO technology (name, description) VALUES ('Red', 'Continue increase process top party.');
INSERT INTO technology (name, description) VALUES ('Vala', 'Reveal world mission.');
INSERT INTO technology (name, description) VALUES ('DataFlex', 'Left group federal good number doctor really participant.');
INSERT INTO technology (name, description) VALUES ('B', 'Political pull concern program house ask executive.');
INSERT INTO technology (name, description) VALUES ('R++', 'South on choice yard.');
INSERT INTO technology (name, description) VALUES ('Processing.js', 'Whether throughout drive through.');
INSERT INTO technology (name, description) VALUES ('Kodu', 'Soldier future high election huge.');
INSERT INTO technology (name, description) VALUES ('Executable UML', 'Purpose whatever admit have return.');
INSERT INTO technology (name, description) VALUES ('BCPL', 'Recognize generation southern relate.');
INSERT INTO technology (name, description) VALUES ('Edinburgh IMP', 'Six degree indicate meet stuff doctor.');
INSERT INTO technology (name, description) VALUES ('AMPL', 'Four model level product.');
INSERT INTO technology (name, description) VALUES ('EGL', 'Truth television baby arm beautiful debate away.');
INSERT INTO technology (name, description) VALUES ('LANSA', 'Course I today though million true.');
INSERT INTO technology (name, description) VALUES ('MATLAB', 'Relationship under free.');
INSERT INTO technology (name, description) VALUES ('LC-3', 'Know then gun move our.');
INSERT INTO technology (name, description) VALUES ('IBM Basic assembly language', 'When off wrong only.');
INSERT INTO technology (name, description) VALUES ('Red', 'Do least pick half loss can.');
INSERT INTO technology (name, description) VALUES ('PL/S', 'Respond nice together assume theory sure west while.');
INSERT INTO technology (name, description) VALUES ('L', 'Team pass town start.');
INSERT INTO technology (name, description) VALUES ('Scratch', 'Third person music rule.');
INSERT INTO technology (name, description) VALUES ('ObjectLOGO', 'Which personal recent body.');
INSERT INTO technology (name, description) VALUES ('GOTRAN', 'Where Congress without painting.');
INSERT INTO technology (name, description) VALUES ('bc', 'Current drug job action wall happy.');
INSERT INTO technology (name, description) VALUES ('Eiffel', 'Dark rich summer worker.');
INSERT INTO technology (name, description) VALUES ('Agilent VEE', 'Model prevent season serious brother create Democrat design.');
INSERT INTO technology (name, description) VALUES ('Visual Objects', 'When stand PM treat worry result through.');
INSERT INTO technology (name, description) VALUES ('XQuery', 'Rock property identify from sea.');
INSERT INTO technology (name, description) VALUES ('Kotlin', 'Per because cup above toward site.');
INSERT INTO technology (name, description) VALUES ('LSE', 'Woman we professor goal.');
INSERT INTO technology (name, description) VALUES ('LSL', 'Reveal draw answer performance rate fund American sport.');
INSERT INTO technology (name, description) VALUES ('Y', 'He bit child actually network bring analysis.');
INSERT INTO technology (name, description) VALUES ('YQL', 'Point sort gun range.');
INSERT INTO technology (name, description) VALUES ('M', 'Language teach go now board interview.');
INSERT INTO technology (name, description) VALUES ('PowerBuilder', 'Than provide modern call itself brother learn.');
INSERT INTO technology (name, description) VALUES ('Clipper', 'Throughout whom consumer season direction another page it.');
INSERT INTO technology (name, description) VALUES ('SIGNAL', 'Simply take eat difference.');
INSERT INTO technology (name, description) VALUES ('ZetaLisp', 'Best meet call kitchen.');
INSERT INTO technology (name, description) VALUES ('Alice ML', 'Money prepare south will laugh professional.');
INSERT INTO technology (name, description) VALUES ('PHP', 'Visit despite guy recognize of environmental year.');
INSERT INTO technology (name, description) VALUES ('Cryptol', 'My size shoulder rate.');
INSERT INTO technology (name, description) VALUES ('BeanShell', 'Director education late note toward green.');
INSERT INTO technology (name, description) VALUES ('Logtalk', 'Community spring room election food point.');
INSERT INTO technology (name, description) VALUES ('Amiga E', 'Feel agree product debate throw skill home.');
INSERT INTO technology (name, description) VALUES ('Opal', 'Arm charge chair wide.');
INSERT INTO technology (name, description) VALUES ('POP-11', 'Different pressure represent red trial account.');
INSERT INTO technology (name, description) VALUES ('Visual Prolog', 'May whole return happen movement.');
INSERT INTO technology (name, description) VALUES ('REBOL', 'Few size project film.');
INSERT INTO technology (name, description) VALUES ('Project Verona', 'Threat type whole former.');
INSERT INTO technology (name, description) VALUES ('Cython', 'Tell available book address special wait a.');
INSERT INTO technology (name, description) VALUES ('Pharo', 'Tend may debate kitchen media price Mr.');
INSERT INTO technology (name, description) VALUES ('ChucK', 'However occur environmental set.');
INSERT INTO technology (name, description) VALUES ('PL/SQL', 'Officer ok already remember fly.');
INSERT INTO technology (name, description) VALUES ('FOCUS', 'Least maintain decide federal middle.');
INSERT INTO technology (name, description) VALUES ('Haskell', 'Where responsibility live teach career.');
INSERT INTO technology (name, description) VALUES ('GDScript', 'Ever citizen water.');
INSERT INTO technology (name, description) VALUES ('Napier88', 'Girl change shoulder real memory capital garden.');
INSERT INTO technology (name, description) VALUES ('High Level Assembly', 'Next account lay.');
INSERT INTO technology (name, description) VALUES ('PHP', 'Fire economic discuss apply someone note force.');
INSERT INTO technology (name, description) VALUES ('JASS', 'Detail several owner.');
INSERT INTO technology (name, description) VALUES ('Pure Data', 'Future international performance determine both ten right skin.');
INSERT INTO technology (name, description) VALUES ('SenseTalk', 'Voice never at prove certainly.');
INSERT INTO technology (name, description) VALUES ('Dog', 'Age save help quality.');
INSERT INTO technology (name, description) VALUES ('Octave', 'Down now board might resource subject.');
INSERT INTO technology (name, description) VALUES ('Claire', 'Seek administration smile fire man kitchen month international.');
INSERT INTO technology (name, description) VALUES ('Zig', 'When you program hear.');
INSERT INTO technology (name, description) VALUES ('Euclid', 'Between color address although cover wind strategy page.');
INSERT INTO technology (name, description) VALUES ('Scilab', 'Often Republican audience positive.');
INSERT INTO technology (name, description) VALUES ('Lasso', 'Far water feel else.');
INSERT INTO technology (name, description) VALUES ('X++', 'Question owner yard goal above study vote other.');
INSERT INTO technology (name, description) VALUES ('LIL', 'Police year five.');
INSERT INTO technology (name, description) VALUES ('TeX', 'Team floor floor itself understand.');
INSERT INTO technology (name, description) VALUES ('A.NET', 'Culture also upon.');
INSERT INTO technology (name, description) VALUES ('Snowball', 'Set wonder white wrong degree all here close.');
INSERT INTO technology (name, description) VALUES ('Scala', 'Agency young design want some scene.');
INSERT INTO technology (name, description) VALUES ('High Level Shader Language', 'Oil play day Republican nearly catch care.');
INSERT INTO technology (name, description) VALUES ('PEARL', 'A already write onto state production either coach.');
INSERT INTO technology (name, description) VALUES ('SPS', 'Read executive necessary.');
INSERT INTO technology (name, description) VALUES ('DinkC', 'Woman pay go pass movement.');
INSERT INTO technology (name, description) VALUES ('Language H', 'Beat number current.');
INSERT INTO technology (name, description) VALUES ('Xtend', 'Guess water prove score get their.');
INSERT INTO technology (name, description) VALUES ('Z', 'Only prepare town season reflect prepare.');
INSERT INTO technology (name, description) VALUES ('Red', 'Authority between within because capital city morning tend.');
INSERT INTO technology (name, description) VALUES ('Actor', 'Not laugh issue painting pressure seat.');
INSERT INTO technology (name, description) VALUES ('FoxBase/FoxPro', 'Price any without the difficult hundred day.');
INSERT INTO technology (name, description) VALUES ('Visual FoxPro', 'Response cell your figure amount term art.');
INSERT INTO technology (name, description) VALUES ('Emacs Lisp', 'He leg blue book Republican front glass few.');
INSERT INTO technology (name, description) VALUES ('Ladder', 'See edge best in movement listen.');
INSERT INTO technology (name, description) VALUES ('Zebra', 'Three seek senior foot nor just.');
INSERT INTO technology (name, description) VALUES ('E', 'Away throw it.');
INSERT INTO technology (name, description) VALUES ('XOTcl', 'Body personal must.');
INSERT INTO technology (name, description) VALUES ('Turing', 'Economic change seven.');
INSERT INTO technology (name, description) VALUES ('Euler', 'Middle later assume win sound.');
INSERT INTO technology (name, description) VALUES ('Cg', 'Area study rate again newspaper they already.');
INSERT INTO technology (name, description) VALUES ('Mirah', 'Ago position assume move participant walk.');
INSERT INTO technology (name, description) VALUES ('Cayenne', 'Story particular employee sign player.');
INSERT INTO technology (name, description) VALUES ('Eiffel', 'Name analysis current continue decide guy.');
INSERT INTO technology (name, description) VALUES ('Scala', 'Whom tough may partner result return everyone way.');
INSERT INTO technology (name, description) VALUES ('Bash', 'Good color wall serious stage event.');
INSERT INTO technology (name, description) VALUES ('Lite-C', 'Summer national ability her.');
INSERT INTO technology (name, description) VALUES ('Mirah', 'Doctor just exist service public wish defense.');
INSERT INTO technology (name, description) VALUES ('Executable UML', 'Morning team hundred degree.');
INSERT INTO technology (name, description) VALUES ('Script.NET', 'Others become into according total environment range.');
INSERT INTO technology (name, description) VALUES ('O', 'Stock scientist center while oil effort nice this.');
INSERT INTO technology (name, description) VALUES ('Visual DataFlex', 'Practice group open such.');
INSERT INTO technology (name, description) VALUES ('GEORGE', 'Lose determine image evening value result light.');
INSERT INTO technology (name, description) VALUES ('MPD', 'Including hundred fast window meeting energy question.');
INSERT INTO technology (name, description) VALUES ('OpenCL', 'Outside computer across between add leg behavior.');
INSERT INTO technology (name, description) VALUES ('LLL', 'Real green option.');
INSERT INTO technology (name, description) VALUES ('LilyPond', 'Information become easy because everybody.');
INSERT INTO technology (name, description) VALUES ('X++', 'Him party air.');
INSERT INTO technology (name, description) VALUES ('PLEXIL', 'Skin dog partner owner cold spend article just.');
INSERT INTO technology (name, description) VALUES ('Klerer-May System', 'Rich baby various.');
