INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mary Key', 'South Kaylastad', '89335', 'United Kingdom', 1);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Johnson Coves', 'Campbellview', '06948', 'Maldives', 2);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hill Ramp', 'Wrightburgh', '81532', 'Sao Tome and Principe', 3);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Zachary Junctions', 'Gomezberg', '34078', 'Congo', 4);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Webb Wall', 'Port Mary', '91662', 'Libyan Arab Jamahiriya', 5);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Walton Street', 'New Carolyn', '48653', 'Norfolk Island', 6);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Timothy Drive', 'East Michaelton', '33414', 'United States of America', 7);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Duncan Junctions', 'New James', '05743', 'Senegal', 8);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stacey Ford', 'Campbellhaven', '26641', 'Moldova', 9);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Melissa Isle', 'Wadeport', '57089', 'Qatar', 10);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jacob Wall', 'East Oliviashire', '76759', 'Papua New Guinea', 11);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Bryant Islands', 'Andrewview', '02288', 'Indonesia', 12);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Valerie Green', 'New Jenniferview', '68582', 'Saint Kitts and Nevis', 13);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kennedy Fall', 'South Joannaberg', '49456', 'Bolivia', 14);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Laura Summit', 'Jennifermouth', '65419', 'Egypt', 15);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Christina Lane', 'Port John', '28594', 'Comoros', 16);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Murray Valleys', 'Ayalatown', '02675', 'Brunei Darussalam', 17);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Pamela Loaf', 'Christopherton', '54504', 'Tonga', 18);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Bradley Village', 'Port Jared', '87001', 'Congo', 19);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Nelson Dam', 'Andreville', '01784', 'Ethiopia', 20);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brian Lodge', 'West Amanda', '00627', 'South Africa', 21);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Fisher Underpass', 'Bowershaven', '24351', 'Saint Kitts and Nevis', 22);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Dillon Locks', 'Mortonfort', '72515', 'Cyprus', 23);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joseph Alley', 'Adamsfort', '21157', 'Moldova', 24);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wood Haven', 'East James', '29102', 'Netherlands Antilles', 25);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joseph Ridge', 'Hendrickshaven', '67341', 'Cambodia', 26);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Bowman Drive', 'South Josephbury', '18122', 'India', 27);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Nicole Locks', 'Lake Thomas', '96876', 'Thailand', 28);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('John Islands', 'East Veronicashire', '97792', 'Cuba', 29);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kevin Haven', 'Meyerton', '73497', 'Trinidad and Tobago', 30);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Ellison Turnpike', 'Brownberg', '81771', 'Netherlands Antilles', 31);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Johnson Plains', 'Petersenland', '00814', 'Saint Pierre and Miquelon', 32);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Peters Fall', 'Riverastad', '34721', 'Afghanistan', 33);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sosa Avenue', 'East Jenniferside', '11513', 'Turkey', 34);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lisa Loop', 'Blackton', '48306', 'Saint Kitts and Nevis', 35);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Keith Center', 'East Donald', '09276', 'Puerto Rico', 36);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hoover Expressway', 'North Johnmouth', '84341', 'Botswana', 37);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cheryl Mills', 'Cruzville', '11705', 'Denmark', 38);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Justin Views', 'Johnchester', '02256', 'British Indian Ocean Territory (Chagos Archipelago)', 39);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('White Mount', 'Lake Paul', '05551', 'Thailand', 40);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Dustin Mall', 'Lake Chase', '31696', 'Congo', 41);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Pacheco Islands', 'Bensonborough', '33708', 'Trinidad and Tobago', 42);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kelly Fords', 'North Joseph', '28072', 'Holy See (Vatican City State)', 43);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Schmidt Circles', 'West Jacqueline', '84674', 'Russian Federation', 44);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jennifer Creek', 'Garciaville', '77467', 'Iran', 45);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('April Trail', 'West Christine', '61461', 'Libyan Arab Jamahiriya', 46);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Miller Circle', 'South Andreaton', '65300', 'Bahamas', 47);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sparks Tunnel', 'New Thomas', '26248', 'Tuvalu', 48);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cory Via', 'South Samuel', '42592', 'Eritrea', 49);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rachel Stream', 'North Charles', '40338', 'Saint Barthelemy', 50);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Conley Springs', 'Kimberlystad', '44383', 'Nepal', 51);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Billy Parkways', 'East Kristenview', '54060', 'Brazil', 52);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jeff Course', 'Barberbury', '38096', 'Iceland', 53);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Woodard Parks', 'Dawnstad', '96299', 'French Southern Territories', 54);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cynthia Square', 'Lake Andrewmouth', '66663', 'Slovenia', 55);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hall Circle', 'Rodriguezville', '33240', 'Anguilla', 56);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kathryn Island', 'Thomaston', '17421', 'Korea', 57);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Fernandez Plaza', 'Andreaberg', '94828', 'Congo', 58);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Margaret Gardens', 'South Christopherborough', '70930', 'Cocos (Keeling) Islands', 59);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Amanda Manors', 'Christinachester', '69718', 'Hungary', 60);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Gary Landing', 'Joseburgh', '75919', 'Djibouti', 61);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Adkins Islands', 'Wrightstad', '88241', 'Turks and Caicos Islands', 62);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mary Vista', 'New Joanne', '12012', 'Germany', 63);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Owens Street', 'Robertmouth', '67197', 'Micronesia', 64);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Robert Trail', 'East Nathan', '98427', 'Kyrgyz Republic', 65);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Phillips Knoll', 'East Michael', '41094', 'South Africa', 66);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Gibson Stream', 'Josephborough', '61529', 'Norfolk Island', 67);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Francis Union', 'New Makayla', '23293', 'Moldova', 68);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wagner Stravenue', 'East Mackenzie', '74698', 'Cote dIvoire', 69);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('James Ridge', 'Millershire', '03219', 'Cook Islands', 70);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hart Circle', 'West Jenniferfort', '67017', 'American Samoa', 71);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Odom Freeway', 'Taylorton', '75427', 'Bangladesh', 72);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cabrera Mission', 'Karistad', '87378', 'Ghana', 73);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cook Gardens', 'Jennifertown', '23972', 'Uruguay', 74);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Anthony Alley', 'Port Brittneyhaven', '90538', 'Jamaica', 75);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Carlos Springs', 'West Miguelfurt', '74464', 'Netherlands Antilles', 76);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Gregory Court', 'Janiceton', '16127', 'Trinidad and Tobago', 77);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Michelle Causeway', 'Christyburgh', '50694', 'Samoa', 78);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brown Mill', 'Johnsonview', '81252', 'Micronesia', 79);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Medina Points', 'Rickyshire', '43046', 'Algeria', 80);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rita Forge', 'Carolhaven', '31280', 'Aruba', 81);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jackson Shore', 'Jessicahaven', '70809', 'South Georgia and the South Sandwich Islands', 82);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kiara Locks', 'Austinshire', '99868', 'Nauru', 83);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Bailey Rapids', 'Lisaburgh', '95132', 'Liberia', 84);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Byrd Ports', 'North Richard', '28813', 'Armenia', 85);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brown Station', 'Port Ericaborough', '17134', 'Dominica', 86);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Daniel Lock', 'Port Heather', '24821', 'United States Minor Outlying Islands', 87);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hayden Ville', 'East Melissafort', '04440', 'French Polynesia', 88);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Alexander Trail', 'North Cynthia', '33901', 'Marshall Islands', 89);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Linda Islands', 'Yorkbury', '87852', 'Bermuda', 90);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Vaughn Points', 'Henryton', '21852', 'Angola', 91);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Peter Brooks', 'Murphyberg', '66096', 'Panama', 92);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Victoria Brook', 'Port Ashley', '49738', 'Northern Mariana Islands', 93);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Miller Station', 'Sarahbury', '01330', 'Lebanon', 94);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('John Road', 'Petershaven', '30444', 'Bahamas', 95);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Anderson Ferry', 'Debrachester', '94834', 'Swaziland', 96);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hancock Tunnel', 'Nicholasborough', '32502', 'Saint Lucia', 97);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Johnson Coves', 'North Kaitlin', '12466', 'Senegal', 98);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Meghan Port', 'East Ryan', '21087', 'Barbados', 99);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Johnny Village', 'Jacquelineview', '16128', 'Barbados', 100);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Andrew Lock', 'Jessicafort', '82849', 'Congo', 101);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jones Glen', 'Horneland', '52620', 'British Virgin Islands', 102);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jared View', 'West Mauriceview', '43804', 'Japan', 103);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Bowman Squares', 'Derekland', '27444', 'Grenada', 104);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Foster Lock', 'Lake Josephton', '54293', 'Kiribati', 105);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lopez Throughway', 'South Sara', '15556', 'Afghanistan', 106);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Thornton Way', 'Kaylaland', '68302', 'Bermuda', 107);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Benjamin Squares', 'Lake Rachel', '80287', 'Thailand', 108);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cox Loaf', 'North Angela', '62664', 'Ghana', 109);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Edwin Center', 'Christopherhaven', '96274', 'Antigua and Barbuda', 110);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Dominguez Point', 'South Karenport', '68693', 'Guinea', 111);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Shelley Orchard', 'Chadport', '99082', 'Mayotte', 112);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Elliott Circles', 'Port Jessica', '34741', 'Slovakia (Slovak Republic)', 113);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Melissa Ports', 'Youngton', '19945', 'Cocos (Keeling) Islands', 114);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jones Land', 'Lake David', '24035', 'Saint Barthelemy', 115);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Robinson Rapids', 'Chelseaburgh', '86842', 'South Africa', 116);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('James Mission', 'North Kaylee', '53441', 'South Africa', 117);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mindy Tunnel', 'Jenniferchester', '06167', 'Egypt', 118);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Melissa Extension', 'Deborahland', '65825', 'Cameroon', 119);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Keith Stream', 'South Kenneth', '20435', 'New Caledonia', 120);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Samuel Circles', 'West Christineland', '09336', 'Nepal', 121);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Amanda Knoll', 'Lake Patrick', '97915', 'Thailand', 122);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Perez Road', 'West Juliahaven', '58688', 'Turkey', 123);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Carroll Circles', 'Jeffreychester', '62745', 'Luxembourg', 124);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Pennington Circle', 'Chrischester', '06351', 'Guinea-Bissau', 125);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Elizabeth Springs', 'Port Adamshire', '91898', 'New Caledonia', 126);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Horn Plaza', 'Chadstad', '79427', 'Sudan', 127);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Anderson Freeway', 'East Allison', '34517', 'Costa Rica', 128);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wade Ford', 'Brownview', '89529', 'Costa Rica', 129);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Newton Ports', 'North Kevinberg', '46169', 'Albania', 130);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Robinson Underpass', 'East Brianstad', '95207', 'France', 131);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lisa Ford', 'Shepardmouth', '17303', 'Wallis and Futuna', 132);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Amber Summit', 'East Jamie', '33034', 'Taiwan', 133);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Angie Rest', 'East Katherine', '43986', 'Bulgaria', 134);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Michael Mill', 'Port Johnmouth', '06333', 'Sierra Leone', 135);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Samantha Land', 'Macdonaldstad', '94421', 'Cook Islands', 136);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Marc Centers', 'Port Ryan', '30190', 'Australia', 137);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Green Islands', 'North Dana', '42183', 'Afghanistan', 138);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jeffrey Via', 'Port Kristophermouth', '81026', 'Congo', 139);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Allen Squares', 'East Jillborough', '18275', 'United States Minor Outlying Islands', 140);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Alexandra Crescent', 'North Anthony', '51732', 'Honduras', 141);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joseph Bridge', 'Rebeccahaven', '67101', 'Haiti', 142);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wallace Ways', 'New Benjaminshire', '65612', 'Turkmenistan', 143);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Berry Keys', 'West Cathyport', '42285', 'Jersey', 144);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Timothy Run', 'Michelleview', '38372', 'Guinea-Bissau', 145);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sanford Garden', 'New Claudiaport', '77441', 'Serbia', 146);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Phillips Plaza', 'East Miranda', '52632', 'Antigua and Barbuda', 147);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('April Brook', 'Emilyside', '22112', 'South Africa', 148);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Carlson Harbor', 'North Laura', '44275', 'Nauru', 149);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brown Parks', 'Scottshire', '73793', 'Argentina', 150);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sarah Drive', 'North Feliciashire', '20039', 'Guinea-Bissau', 151);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joshua Ferry', 'Christinaburgh', '79998', 'Montserrat', 152);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Tonya Burg', 'West Heatherstad', '38672', 'Korea', 153);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Fuller Stream', 'Port Katelyn', '02407', 'Aruba', 154);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rodriguez Lane', 'Knightville', '37971', 'American Samoa', 155);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Craig Ridge', 'Leefort', '09438', 'Monaco', 156);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hall Village', 'West Kevin', '53038', 'Faroe Islands', 157);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Beck Throughway', 'Port Angela', '97905', 'Oman', 158);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('White Fall', 'Walkerchester', '52780', 'Jersey', 159);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sharp Lock', 'South Jason', '98945', 'Korea', 160);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mitchell Estate', 'South Jessicashire', '37113', 'Niue', 161);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cunningham Cliff', 'Weeksland', '14084', 'Bangladesh', 162);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Zachary Station', 'Sarabury', '75007', 'Saint Pierre and Miquelon', 163);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Tracy Prairie', 'Clarkburgh', '21850', 'Korea', 164);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sharp Parkway', 'Jimmyhaven', '50634', 'Panama', 165);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Williams Neck', 'North Mariafurt', '82919', 'Lesotho', 166);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Martinez Plain', 'Port Ashleymouth', '28615', 'Ghana', 167);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Keith Inlet', 'North Michaelfort', '31179', 'Russian Federation', 168);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stewart Union', 'Savagetown', '32357', 'Australia', 169);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('James Trafficway', 'North Jason', '41993', 'Iceland', 170);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('James Forks', 'South Joseph', '30131', 'Congo', 171);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Nathaniel Station', 'North Phillip', '27604', 'Nigeria', 172);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Tami Inlet', 'Jonathanchester', '59870', 'Denmark', 173);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Williams Lodge', 'Jenniferstad', '66497', 'Guernsey', 174);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mcconnell Corners', 'Port Robertton', '36408', 'Comoros', 175);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Elizabeth Tunnel', 'Katherinetown', '46391', 'Dominica', 176);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mcknight Mews', 'Bradstad', '57972', 'Armenia', 177);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Young Meadows', 'Underwoodburgh', '75136', 'Pakistan', 178);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lewis Mills', 'Melaniehaven', '11126', 'Western Sahara', 179);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Silva Trace', 'West Sean', '04062', 'Sri Lanka', 180);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Michele Springs', 'Guerraland', '99016', 'Micronesia', 181);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wallace Landing', 'Johnsonstad', '41320', 'Nigeria', 182);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hall Neck', 'Deborahstad', '68027', 'Antigua and Barbuda', 183);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Michelle Extensions', 'East Matthewville', '71630', 'Liechtenstein', 184);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joshua Glen', 'New John', '96950', 'Ecuador', 185);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rich Harbors', 'Kingstad', '96645', 'Burkina Faso', 186);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Turner Circle', 'Morrisberg', '56583', 'Romania', 187);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stephanie Junction', 'East Ricky', '24617', 'Montserrat', 188);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Daniel Dam', 'West Heidiside', '94853', 'Montenegro', 189);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kyle Shoals', 'East Danielle', '13230', 'Guinea-Bissau', 190);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cox Islands', 'Sullivanmouth', '37479', 'Wallis and Futuna', 191);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joseph Shore', 'Lake Jason', '22191', 'Togo', 192);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cheryl Green', 'East Brandonmouth', '81902', 'Argentina', 193);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rachel Village', 'Andrefurt', '12986', 'France', 194);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Emily Alley', 'Hillburgh', '20011', 'Norfolk Island', 195);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Santiago Field', 'Michaelport', '13791', 'Hong Kong', 196);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('John Locks', 'Port Erinmouth', '12749', 'Bulgaria', 197);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jimenez Vista', 'Cherylport', '35047', 'Saint Vincent and the Grenadines', 198);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joshua Circle', 'South Nicole', '95443', 'Bahrain', 199);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Ann Squares', 'Cohenmouth', '73727', 'United Kingdom', 200);
