INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wayne Corners', 'Angelaton', '25226', 'Thailand', 43);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Ray Divide', 'North Natasha', '78531', 'Egypt', 25);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stanley Summit', 'Mitchellfurt', '43327', 'Guyana', 69);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Clark Knoll', 'Hannafort', '68345', 'South Georgia and the South Sandwich Islands', 52);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stuart Shore', 'Lake Patrick', '49182', 'Malawi', 149);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kimberly Oval', 'Floreshaven', '33741', 'France', 129);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Luis Island', 'Port Gregory', '29828', 'Senegal', 81);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mark Ville', 'Lake Rachelton', '94490', 'Lithuania', 93);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kane Islands', 'Michaelaberg', '10482', 'Venezuela', 58);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('White Glens', 'Victoriaside', '81562', 'Zimbabwe', 113);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Price Overpass', 'New Christinahaven', '55784', 'Montenegro', 41);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Holloway Road', 'West Elizabeth', '40350', 'Maldives', 122);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brown Rapid', 'Lake Mandyville', '12479', 'Cameroon', 94);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Price Ways', 'West Daniel', '61311', 'Libyan Arab Jamahiriya', 68);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Anne Mountains', 'New Thomas', '21287', 'Indonesia', 161);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Haley Glen', 'Brittanyberg', '47375', 'Uzbekistan', 32);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Holmes Plaza', 'Jacksontown', '63912', 'New Zealand', 91);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Marshall Overpass', 'Lake Madison', '72925', 'United States of America', 161);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kim Place', 'Bellport', '24893', 'Guam', 109);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Marsh Passage', 'Fryefort', '13181', 'Mexico', 103);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wallace Curve', 'South Dean', '90232', 'Nepal', 109);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Bailey Ramp', 'West Melissaside', '80589', 'Lebanon', 113);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cindy Ramp', 'Colemanstad', '04941', 'British Indian Ocean Territory (Chagos Archipelago)', 71);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Antonio Forges', 'South Spencer', '26016', 'Albania', 180);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Richard Alley', 'Schneiderhaven', '98303', 'Madagascar', 115);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wood Plains', 'Port Kevinborough', '22260', 'Liechtenstein', 118);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hendrix Unions', 'Johnsonland', '42921', 'Nepal', 2);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Michael Courts', 'Gonzalezberg', '58939', 'Oman', 136);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Barnes Turnpike', 'Lake Dianeville', '71019', 'Timor-Leste', 87);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Aaron Path', 'North Melindabury', '47619', 'Turkey', 26);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Elizabeth Brooks', 'South Ashley', '38652', 'Syrian Arab Republic', 20);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Vasquez Estate', 'Jamesside', '14544', 'Philippines', 114);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Deborah Greens', 'South Stephanie', '28590', 'Guadeloupe', 142);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Williams Ferry', 'Sullivanborough', '96274', 'Mongolia', 129);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brittany Prairie', 'South John', '09168', 'Zambia', 187);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('King Crest', 'Santostown', '39188', 'Guadeloupe', 167);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brendan River', 'Cortezside', '88201', 'Italy', 20);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Raymond Station', 'Thomasburgh', '29650', 'American Samoa', 200);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Vincent Rapid', 'Clintonport', '61605', 'Cayman Islands', 152);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rodriguez Key', 'Frymouth', '52829', 'Spain', 62);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Matthew Plains', 'South Scottborough', '31657', 'Bangladesh', 113);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Dunn Route', 'Markmouth', '93934', 'Pitcairn Islands', 36);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Clark Trafficway', 'Wrightport', '44110', 'Dominica', 102);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jessica Locks', 'Brittanyborough', '37089', 'Kazakhstan', 188);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Carmen Walks', 'Port Morgan', '15601', 'Bulgaria', 122);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cassandra Drive', 'Jeffreyton', '26942', 'Nigeria', 166);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('King Tunnel', 'Martinshire', '39978', 'Saint Vincent and the Grenadines', 181);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Reynolds Hills', 'Jamesville', '60995', 'Hungary', 65);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sparks Trail', 'Taylorton', '02885', 'Kazakhstan', 143);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stevens Pines', 'Port Diana', '48360', 'Guernsey', 3);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Miller Corner', 'Ortizberg', '60394', 'Cook Islands', 83);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Matthews Rapid', 'Lake Dana', '25098', 'Saint Pierre and Miquelon', 53);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Darin Plains', 'Lake Johnathanfurt', '81901', 'Portugal', 173);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Blanchard Walk', 'New Michael', '80929', 'Lithuania', 102);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Nathan Row', 'Davisport', '50106', 'Rwanda', 55);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Grant Valley', 'Duncanborough', '73637', 'Spain', 85);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Ortega Extensions', 'New Natalie', '52812', 'Timor-Leste', 121);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Landry Lakes', 'North Ericaview', '05038', 'Romania', 176);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Joshua Brook', 'East Bradley', '35291', 'Bahrain', 162);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Andrew Underpass', 'Howardville', '55501', 'Greenland', 18);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('George Heights', 'Madelinemouth', '59345', 'Mongolia', 111);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lori Branch', 'Reginaldberg', '09208', 'Panama', 180);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Eddie Walk', 'Murphyland', '62169', 'Japan', 131);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Frank Falls', 'Lake Jacob', '95389', 'Pitcairn Islands', 126);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Melissa Walk', 'Chapmanberg', '98226', 'Tanzania', 82);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jennifer Loaf', 'West Pamelashire', '09301', 'Uzbekistan', 106);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Turner Fall', 'South Mark', '23937', 'Qatar', 71);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Anthony Mount', 'Amandafort', '09425', 'Solomon Islands', 192);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rhodes Dam', 'West Bradton', '79074', 'Colombia', 137);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wheeler Mews', 'Josephton', '81308', 'Saint Vincent and the Grenadines', 108);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Green Summit', 'Andrewborough', '98323', 'Puerto Rico', 83);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Turner Loop', 'North William', '09791', 'Seychelles', 128);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Katherine Trail', 'Carlbury', '79348', 'Faroe Islands', 43);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stewart Mission', 'North Christopherport', '98805', 'Mali', 19);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lauren Mill', 'Ryanhaven', '16445', 'Pitcairn Islands', 144);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jensen Summit', 'New Kaylachester', '37407', 'Pakistan', 46);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Newman Roads', 'Whitneyburgh', '85057', 'Norway', 24);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Alicia Trace', 'Jenkinsshire', '18416', 'Brunei Darussalam', 80);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Melanie Spurs', 'Larsonstad', '90609', 'Bermuda', 113);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Laura Shoal', 'Williamberg', '73902', 'Kiribati', 148);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brenda Inlet', 'Floresville', '57096', 'Liberia', 74);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Victor Corners', 'Navarroside', '50704', 'Tanzania', 19);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Christian Corners', 'New Timothyland', '92916', 'Saint Barthelemy', 10);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lee Stream', 'Port Joe', '81276', 'Seychelles', 36);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('James Underpass', 'Lake Nancy', '06563', 'Singapore', 142);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rivas Station', 'Port Melanietown', '78841', 'Falkland Islands (Malvinas)', 134);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Martin Plaza', 'Lake Tara', '36750', 'Cook Islands', 155);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Santiago Parkways', 'Gravesburgh', '60570', 'Denmark', 115);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Corey Route', 'New Rhonda', '16676', 'Kuwait', 111);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kelsey Way', 'North Joshuatown', '34877', 'Iraq', 9);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Shaffer Brooks', 'Davidborough', '63084', 'Kyrgyz Republic', 129);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Martinez Prairie', 'Carlosshire', '89856', 'Nigeria', 131);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Silva Rue', 'East Jamie', '24381', 'Turkey', 49);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cindy Freeway', 'Dennismouth', '28323', 'Luxembourg', 85);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Max Fields', 'Port Abigail', '94488', 'Norway', 137);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('William Fields', 'East Jeremystad', '73898', 'United States Virgin Islands', 181);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Peterson Roads', 'Lauriechester', '60243', 'Antarctica (the territory South of 60 deg S)', 115);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Alexis Run', 'Lake Darlene', '97037', 'Croatia', 61);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Fitzgerald Pines', 'New Jasonmouth', '07728', 'Guam', 153);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Gregory Point', 'Timothyberg', '79941', 'Ghana', 191);
