INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Alexander Freeway', 'West Dawnfort', '61896', 'Tanzania', 1);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Novak Port', 'West Cynthia', '09400', 'Suriname', 2);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('John Trafficway', 'South Harold', '89085', 'Armenia', 3);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Snyder Unions', 'Gordonside', '20389', 'Spain', 4);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Megan Square', 'West Sara', '16627', 'Honduras', 5);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('White Cliff', 'East Tony', '05892', 'Christmas Island', 6);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kenneth Manor', 'Charlesstad', '82727', 'Nepal', 7);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sims Viaduct', 'Haroldton', '77346', 'Maldives', 8);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jonathan Stream', 'Christinaton', '22719', 'Suriname', 9);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('James Court', 'East Frankville', '67306', 'Senegal', 10);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Elizabeth Springs', 'Christopherland', '48554', 'Bhutan', 11);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jason Estate', 'Farmerborough', '69833', 'Benin', 12);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Donna Stravenue', 'Emilytown', '70480', 'Indonesia', 13);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Davis Road', 'South Steven', '91874', 'Libyan Arab Jamahiriya', 14);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Katherine Lakes', 'Michaelchester', '92302', 'Saint Helena', 15);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Bell Village', 'Port Shawn', '20203', 'Serbia', 16);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('May Glen', 'Mezabury', '22838', 'Cameroon', 17);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Martin Junction', 'Lauramouth', '85577', 'Guam', 18);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jenna Flat', 'Chenfurt', '36372', 'Switzerland', 19);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Guerra Fall', 'East Lucas', '11405', 'Namibia', 20);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Deleon Crossing', 'Port Jamesville', '02729', 'New Zealand', 21);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Maria Mountain', 'East Veronicatown', '72089', 'Gabon', 22);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hendrix Ports', 'Collinshaven', '99481', 'Guernsey', 23);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Gregory Court', 'Andrewsborough', '43870', 'Turkmenistan', 24);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Brenda Stream', 'Christophermouth', '68048', 'Gibraltar', 25);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jodi Village', 'West Zacharyville', '20550', 'Heard Island and McDonald Islands', 26);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kendra Keys', 'Collinsberg', '39564', 'Dominican Republic', 27);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Ashley Run', 'Cooperport', '52451', 'Oman', 28);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sandra Plains', 'Vincentland', '52378', 'Cuba', 29);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Tom Roads', 'Simsborough', '66400', 'British Virgin Islands', 30);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stone Pines', 'Langstad', '00948', 'Aruba', 31);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mitchell Wall', 'New Kim', '11956', 'Kyrgyz Republic', 32);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Adams Port', 'Port Kimhaven', '41832', 'Uruguay', 33);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Juarez Brook', 'South Royborough', '33914', 'Algeria', 34);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Cook Flat', 'New Lisa', '84864', 'Hungary', 35);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Victoria Creek', 'Lake Theresafort', '18094', 'United States Virgin Islands', 36);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Anthony Run', 'Whiteview', '89895', 'Bangladesh', 37);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Dawn Courts', 'West Dawn', '25654', 'Egypt', 38);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Daniel Land', 'Jenniferchester', '71711', 'Mexico', 39);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sonya Club', 'Jasonhaven', '09526', 'Cote dIvoire', 40);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Gibson Island', 'Jesseport', '57146', 'Cote dIvoire', 41);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Pope Key', 'Port Curtisland', '46042', 'Guam', 42);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Wilson Rue', 'Port Danielborough', '34140', 'Northern Mariana Islands', 43);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Hurst Mission', 'Port Dennis', '76001', 'Faroe Islands', 44);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Rebecca Greens', 'South John', '79369', 'Switzerland', 45);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sean Curve', 'Lindsayborough', '45853', 'Tonga', 46);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sandra Oval', 'Lake Mary', '69758', 'French Guiana', 47);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Fuller Mountains', 'Amandaton', '93703', 'Somalia', 48);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Browning Springs', 'Port Caroline', '87965', 'Malta', 49);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Guzman Haven', 'Petersenland', '56494', 'Netherlands', 50);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Lyons Plains', 'North Richardport', '08107', 'Norway', 23);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Annette Roads', 'Taylorland', '86090', 'Nepal', 32);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Ashley Locks', 'Lake Chelseyville', '76945', 'Congo', 27);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Smith Mount', 'East Alexandra', '24344', 'Macao', 35);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Mckenzie Squares', 'East Gregorymouth', '25198', 'Qatar', 31);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Stevens Lodge', 'Paulside', '23413', 'Burkina Faso', 11);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Barrera Inlet', 'South Kimland', '38986', 'Benin', 25);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Sanders Falls', 'Higginsmouth', '31359', 'Saint Pierre and Miquelon', 26);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Nicholas Path', 'Hernandezmouth', '78377', 'Eritrea', 40);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Simpson Coves', 'Meganhaven', '83721', 'Tonga', 15);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Michael Green', 'East Matthewshire', '86368', 'Suriname', 5);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Leblanc Lights', 'Lauraville', '68872', 'Cambodia', 23);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Shelly View', 'West Sharon', '94928', 'Uzbekistan', 49);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Dustin Estates', 'Pamelaland', '31294', 'China', 49);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Charles Lodge', 'Hesterbury', '50504', 'Fiji', 33);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Finley Rest', 'Lake Gwendolyn', '56252', 'Moldova', 19);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Kimberly Lane', 'North Emilyborough', '07211', 'Pakistan', 30);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jeremy Estates', 'Jonesstad', '90053', 'Timor-Leste', 28);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Williams Fords', 'Johnsonside', '99301', 'Micronesia', 31);
INSERT INTO address (street, city, postal_code, country, company_id) VALUES ('Jennifer Green', 'West Scottfurt', '44927', 'Pakistan', 35);
