INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (1, 196, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (1, 26, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (1, 79, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (2, 80, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (2, 199, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (2, 17, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (2, 185, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (3, 87, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (3, 53, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (4, 50, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (4, 30, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (4, 110, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (4, 40, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (5, 176, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (5, 135, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (6, 132, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (7, 78, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (8, 167, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (8, 71, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (9, 131, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (9, 47, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (9, 140, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (9, 95, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (10, 171, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (10, 86, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (10, 108, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (11, 133, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (11, 27, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (11, 62, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (12, 43, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (12, 65, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (13, 106, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (13, 125, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (13, 161, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (13, 59, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (14, 156, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (15, 146, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (15, 130, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (16, 193, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (16, 102, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (16, 151, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (17, 31, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (17, 125, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (17, 88, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (18, 61, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (18, 160, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (18, 104, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (19, 82, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (19, 184, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (19, 66, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (19, 137, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (19, 65, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (20, 106, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (20, 59, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (21, 17, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (22, 60, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (22, 21, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (22, 116, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (22, 193, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (23, 8, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (23, 197, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (23, 156, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (23, 141, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (23, 51, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (24, 175, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (24, 195, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (25, 48, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (26, 109, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (26, 125, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (26, 121, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (26, 159, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (26, 147, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (27, 135, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (27, 23, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (28, 129, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (28, 138, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (28, 112, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (29, 134, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (29, 99, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (29, 106, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (30, 182, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (30, 74, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (30, 10, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (30, 197, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (30, 184, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (31, 126, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (32, 98, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (32, 22, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (33, 30, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (33, 85, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (33, 52, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (33, 126, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (33, 86, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (34, 189, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (34, 158, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (34, 147, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (35, 37, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (35, 25, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (35, 141, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (35, 131, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (35, 21, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (36, 195, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (37, 50, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (37, 125, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (37, 2, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (38, 28, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (38, 110, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (38, 100, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (38, 175, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (38, 170, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (39, 76, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (39, 52, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (39, 156, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (39, 131, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (40, 15, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (40, 173, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (40, 81, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (40, 13, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (41, 123, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (41, 83, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (41, 113, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (41, 16, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (41, 103, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (42, 121, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (42, 37, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (42, 115, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (43, 95, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (43, 163, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (44, 59, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (44, 184, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (44, 17, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (44, 1, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (44, 107, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (45, 11, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (45, 89, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (46, 40, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (47, 39, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (47, 176, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (47, 83, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (47, 93, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (47, 107, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (48, 74, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (49, 129, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (49, 177, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (49, 69, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (49, 111, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (50, 46, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (50, 27, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (50, 82, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (51, 134, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (51, 46, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (52, 14, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (52, 20, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (52, 42, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (52, 51, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (52, 113, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (53, 29, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (53, 138, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (53, 198, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (54, 111, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (55, 89, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (55, 18, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (56, 85, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (57, 199, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (57, 175, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (57, 46, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (57, 130, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (58, 131, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (58, 63, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (58, 81, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (59, 43, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (59, 180, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (59, 136, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (60, 99, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (61, 55, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (62, 79, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (62, 134, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (63, 19, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (63, 151, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (63, 173, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (63, 92, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (63, 23, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (64, 105, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (64, 185, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (64, 12, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (64, 200, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (65, 146, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (65, 63, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (65, 16, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (65, 175, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (66, 13, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (66, 22, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (67, 90, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (67, 24, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (67, 125, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (67, 131, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (68, 37, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (68, 38, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (68, 78, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (68, 15, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (68, 188, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (69, 173, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (69, 4, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (70, 161, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (70, 187, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (70, 198, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (70, 45, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (71, 22, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (71, 134, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (72, 161, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (73, 175, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (73, 194, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (73, 132, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (73, 6, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (74, 99, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (74, 57, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (74, 34, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (74, 157, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (74, 100, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (75, 23, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (76, 182, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (77, 5, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (77, 142, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (78, 139, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (78, 133, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (78, 118, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (78, 151, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (79, 177, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (79, 82, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (79, 7, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (80, 78, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (80, 195, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (80, 142, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (80, 2, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (81, 174, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (82, 22, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (82, 61, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (82, 52, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (82, 62, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (83, 166, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (83, 103, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (83, 165, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (84, 110, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (84, 134, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (84, 122, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (85, 66, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (85, 92, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (85, 154, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (85, 160, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (86, 29, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (87, 166, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (87, 114, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (87, 55, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (88, 114, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (88, 31, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (89, 196, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (89, 54, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (90, 198, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (90, 164, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (90, 39, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (90, 147, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (91, 100, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (91, 103, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (91, 196, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (92, 131, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (92, 189, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (92, 194, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (92, 141, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (93, 174, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (93, 146, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (93, 24, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (94, 68, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (94, 128, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (94, 42, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (95, 126, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (95, 40, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (96, 142, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (97, 116, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (97, 25, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (97, 168, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (97, 166, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (98, 119, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (98, 6, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (98, 83, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (99, 162, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (100, 96, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (100, 81, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (100, 160, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (100, 162, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (101, 4, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (101, 26, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (102, 79, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (102, 92, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (102, 95, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (102, 84, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (102, 152, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (103, 48, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (103, 69, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (103, 188, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (103, 120, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (104, 94, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (104, 45, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (105, 135, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (105, 11, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (105, 134, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (106, 185, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (106, 45, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (107, 70, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (108, 13, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (108, 92, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (108, 18, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (108, 89, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (109, 38, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (109, 107, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (109, 146, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (109, 37, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (110, 81, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (110, 32, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (110, 64, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (110, 88, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (111, 48, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (111, 54, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (111, 73, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (112, 129, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (112, 14, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (112, 35, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (112, 27, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (113, 1, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (113, 138, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (113, 100, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (113, 87, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (113, 157, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (114, 179, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (115, 41, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (116, 10, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (116, 2, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (116, 28, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (117, 134, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (117, 56, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (117, 99, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (117, 13, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (117, 139, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (118, 193, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (118, 147, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (118, 115, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (119, 199, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (119, 57, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (119, 114, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (120, 125, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (120, 33, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (121, 53, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (121, 12, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (122, 52, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (122, 199, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (122, 179, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (122, 114, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (122, 108, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (123, 186, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (123, 118, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (123, 66, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (123, 187, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (123, 39, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (124, 35, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (124, 71, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (125, 123, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (125, 199, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (125, 155, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (125, 55, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (126, 110, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (127, 102, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (127, 148, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (127, 78, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (128, 89, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (128, 189, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (128, 171, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (129, 159, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (129, 109, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (129, 169, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (129, 151, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (129, 135, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (130, 76, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (130, 158, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (130, 182, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (130, 114, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (130, 195, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (131, 156, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (131, 172, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (131, 75, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (131, 155, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (132, 13, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (132, 193, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (132, 188, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (132, 28, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (133, 101, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (133, 78, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (134, 182, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (134, 120, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (134, 199, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (135, 174, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (135, 41, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (136, 74, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (136, 44, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (137, 135, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (137, 30, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (138, 28, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (139, 174, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (139, 50, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (139, 7, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (139, 140, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (140, 129, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (141, 193, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (141, 56, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (141, 134, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (142, 156, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (142, 56, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (142, 155, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (142, 125, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (143, 56, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (143, 97, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (143, 117, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (143, 34, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (144, 159, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (144, 78, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (145, 132, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (145, 79, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (145, 155, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (145, 109, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (146, 101, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (146, 135, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (146, 58, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (146, 99, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (147, 18, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (147, 147, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (147, 94, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (148, 50, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (148, 85, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (148, 190, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (148, 81, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (149, 46, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (149, 108, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (149, 98, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (149, 85, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (149, 76, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (150, 49, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (151, 46, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (151, 37, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (151, 31, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (151, 87, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (152, 60, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (152, 9, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (152, 58, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (153, 184, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (153, 17, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (153, 148, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (153, 35, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (153, 81, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (154, 54, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (154, 101, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (154, 99, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (154, 165, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (155, 25, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (155, 122, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (155, 130, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (155, 51, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (155, 123, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (156, 126, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (156, 4, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (156, 123, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (156, 132, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (156, 147, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (157, 107, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (157, 150, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (157, 91, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (158, 46, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (158, 72, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (159, 42, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (159, 121, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (159, 18, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (160, 141, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (160, 53, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (160, 5, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (161, 151, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (161, 116, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (161, 195, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (162, 195, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (162, 110, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (162, 119, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (162, 132, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (163, 40, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (163, 19, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (163, 41, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (163, 50, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (164, 69, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (164, 42, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (165, 123, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (165, 116, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (166, 79, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (166, 176, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (166, 179, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (166, 111, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (167, 18, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (167, 1, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (167, 38, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (167, 33, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (168, 119, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (169, 73, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (170, 176, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (170, 73, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (170, 61, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (170, 2, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (170, 68, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (171, 49, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (171, 137, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (172, 193, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (173, 105, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (174, 6, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (174, 190, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (174, 25, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (175, 77, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (176, 75, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (176, 78, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (176, 88, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (176, 69, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (177, 191, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (177, 140, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (177, 198, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (177, 6, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (177, 77, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (178, 155, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (178, 43, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (178, 87, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (179, 86, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (180, 144, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (180, 43, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (180, 41, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (180, 133, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (180, 165, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (181, 13, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (181, 182, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (181, 163, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (182, 129, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (182, 72, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (182, 5, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (182, 188, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (182, 67, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (183, 144, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (183, 120, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (183, 72, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (183, 87, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (183, 95, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (184, 187, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (184, 181, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (185, 196, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (185, 15, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (185, 80, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (185, 134, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (185, 39, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (186, 86, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (186, 30, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (186, 17, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (187, 197, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (187, 147, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (187, 103, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (188, 196, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (188, 42, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (188, 100, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (188, 119, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (188, 134, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (189, 170, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (189, 2, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (189, 25, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (189, 105, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (189, 194, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (190, 173, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (190, 82, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (190, 171, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (191, 2, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (191, 195, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (192, 113, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (192, 12, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (192, 198, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (193, 4, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (193, 96, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (194, 24, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (194, 16, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (195, 49, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (195, 57, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (195, 58, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (196, 64, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (196, 79, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (196, 15, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (197, 118, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (197, 18, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (198, 155, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (198, 61, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (198, 156, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (198, 29, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (198, 106, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (199, 19, 'advanced');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (199, 131, 'expert');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (199, 30, 'no knowledge required');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (199, 72, 'beginner');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (200, 87, 'intermediate');
INSERT INTO job_offer_technology (job_offer_id, technology_id, degree_of_knowledge) VALUES (200, 35, 'expert');
